### PR TITLE
HADOOP-16448. Connection to Hadoop homepage is not secure

### PR DESCRIPTION
**Pull request by snemuri**

### CODE REVIEW

**Comment by aajisaka** [comment]
Thanks @snemuri for the patch.

Would you undo the changes in the license header? I'm +1 if that is addressed.
Ref: https://issues.apache.org/jira/browse/HADOOP-16331

**Comment by snemuri** [comment]
@aajisaka Thanks for reviewing. Reverted the changes in license header.

**Comment by aajisaka** [comment]
```
find . -type f | xargs grep "https://www.apache.org/licenses/" | grep -v "href="
./ozone/LICENSE.txt:                        https://www.apache.org/licenses/
./content/docs/r0.23.11/common/LICENSE.txt:                        https://www.apache.org/licenses/
./content/docs/r0.23.11/hdfs/LICENSE.txt:                        https://www.apache.org/licenses/
./content/docs/r0.23.11/mapreduce/LICENSE.txt:                        https://www.apache.org/licenses/
./content/docs/r2.4.1/yarn/LICENSE.txt:                        https://www.apache.org/licenses/
./content/docs/r2.4.1/common/LICENSE.txt:                        https://www.apache.org/licenses/
./content/docs/r2.4.1/hdfs/LICENSE.txt:                        https://www.apache.org/licenses/
./content/docs/r2.4.1/mapreduce/LICENSE.txt:                        https://www.apache.org/licenses/
./submarine/LICENSE.txt:                        https://www.apache.org/licenses/
```
Thank you for the update. In addition, would you revert the changes in the above files?

**Comment by snemuri** [comment]
@aajisaka Made the necessary changes. Kindly review.

**Review by aajisaka — APPROVED** [review]
+1

**Comment by aajisaka** [comment]
Thank you for the contribution, @snemuri !

**Pull request merged**
