### PR TITLE
HDDS-2601: Fix Broken Link In Website

### PR DESCRIPTION
**Pull request by snemuri**

### CODE REVIEW

**Comment by ayushtkn** [comment]
Did you run **hugo** post making the change?
Check the process here :
https://cwiki.apache.org/confluence/display/HADOOP/Modifying+the+Ozone+Website

**Comment by snemuri** [comment]
I did run the `hugo` command.
Few files got updated with hugo versions(with the version number installed in my Mac) hence skipped them.

**Comment by ayushtkn** [comment]
Give a check if you skipped this one too 
https://github.com/apache/hadoop-site/blob/asf-site/content/ozone/faq/index.html

**Comment by snemuri** [comment]
Oops had to run  `hugo` from the ozone directory. Updated the PR. 
Thanks for the review @ayushtkn

**Review by nandakumar131 — APPROVED** [review]

**Pull request merged**
