### PR TITLE
Update README to use Hugo version 0.89.0

### PR DESCRIPTION
**Pull request by GauthamBanasandra**
Different versions of Hugo introduce different
formatting styles. These formatting changes are
unnecessary and makes PR reviews difficult.
Thus, we're documenting the version of Hugo to
adhere to.

### CODE REVIEW

**Comment by GauthamBanasandra** [comment]
@aajisaka could you please review this PR?

**Comment by aajisaka** [comment]
I think we should use the latest version instead of hard-cording.

**Comment by GauthamBanasandra** [comment]
@aajisaka there could be formatting changes between newer releases of Hugo right? Hence, I've fixed the version in this PR.

**Comment by aajisaka** [comment]
Yes, there could be formatting change in the future release. However, I don't think the version should be fixed.

**Comment by GauthamBanasandra** [comment]
Closing this PR since we don't want to fix hugo to a particular version.

**Pull request closed without merging**
