### PR TITLE
Add Gautham Banasandra to Hadoop committers' list

### PR DESCRIPTION
**Pull request by GauthamBanasandra**

### CODE REVIEW

**Comment by GauthamBanasandra** [comment]
@aajisaka could you please review this PR?

**Comment by aajisaka** [comment]
Would you run `hugo` to generate the html files and add them to the commit?

**Comment by GauthamBanasandra** [comment]
@aajisaka I ran the following -
```shell
$ hugo --config config.toml
```

There seems to be a lot of formatting changes. Is it fine? Is there a way to skip formatting in hugo?

**Comment by GauthamBanasandra** [comment]
Hi @gerashegalov,
I see that some formatting changes were introduced as part of your commit - https://github.com/apache/hadoop-site/commit/e0acca4bcd104b72cee5371e89e810e570e6d77a#diff-1a70b83cf2e9824572526571b6dd9894ce14162d330751255da19f8ee1a12c1fL169-L174.
Could you please let me know the parameters that you passed when you ran the `hugo` command so that I can use the same here?

**Comment by gerashegalov** [comment]
Hi @GauthamBanasandra , I am pretty sure that I simply invoked `./hugo` in the repo root without any parameters. README.md does not mention any params.

**Comment by aajisaka** [comment]
I think the formatting change is due to the version of hugo. I'm +1.

**Review by aajisaka — APPROVED** [review]

**Comment by aajisaka** [comment]
Probably `./hugo` in the repo root is committed accidentally. It should be removed.

**Comment by GauthamBanasandra** [comment]
> Probably `./hugo` in the repo root is committed accidentally. It should be removed.

Sure, will do it right away.

**Comment by GauthamBanasandra** [comment]
I've created a PR to delete the hugo binary - https://github.com/apache/hadoop-site/pull/29

**Pull request merged**
