### PR TITLE
ozone: fix typo on index.html

### PR DESCRIPTION
**Pull request by technmsg**

### CODE REVIEW

**Comment by busbey** [comment]
Thanks for the contribution and excellent proof reading catch, @technmsg!

Please excuse the delay while I take care of a project internal administrative thing.

based on a previous typo-fixing commit 6631b7b7720475094cadbc7b6b251009f9f22a0d I'm presuming we're fine with this repo having small fix contributions accepted without requiring a JIRA. If anyone disagrees, please speak up.

**Review by busbey — APPROVED** [review]

**Comment by aajisaka** [comment]
The generation of the site is not automatic (yet), so would you run `hugo` to generate the page and push the content to your branch?

https://cwiki.apache.org/confluence/display/HADOOP/How+to+generate+and+push+ASF+web+site+after+HADOOP-14163

**Comment by aajisaka** [comment]
> based on a previous typo-fixing commit 6631b7b I'm presuming we're fine with this repo having small fix contributions accepted without requiring a JIRA. If anyone disagrees, please speak up.

Agreed.

**Comment by aajisaka** [comment]
> The generation of the site is not automatic (yet), so would you run `hugo` to generate the page and push the content to your branch?
> 
> https://cwiki.apache.org/confluence/display/HADOOP/How+to+generate+and+push+ASF+web+site+after+HADOOP-14163

I'll merge this and then update the content.

**Comment by aajisaka** [comment]
Thanks @technmsg for the contribution!

**Pull request merged**
