### PR TITLE
HADOOP-17664. Fix release change log url error

### PR DESCRIPTION
**Pull request by cutiechi**
Fix release change log url error

### CODE REVIEW

**Comment by aajisaka** [comment]
Hi @cutiechi 
The source change looks good to me. Would you run `hugo` and add the generated HTML files to this pull request?

**Comment by cutiechi** [comment]
@aajisaka Done

**Review by aajisaka — APPROVED** [review]
Thanks

**Comment by ayushtkn** [comment]
We should have updated it here as well?
https://github.com/apache/hadoop-site/blob/asf-site/content/index.html#L297

The link from here is still broken-
https://hadoop.apache.org/

**Comment by cutiechi** [comment]
@ayushtkn I will fix it

**Pull request merged**
