### PR TITLE
Add Shilun Fan to Committer List.

### PR DESCRIPTION
**Pull request by slfan1989**

### CODE REVIEW

**Review by aajisaka — APPROVED** [review]

**Comment by aajisaka** [comment]
Hi @slfan1989 you'll need to follow the following steps to merge the PR via GitHub:

> To use GitHub, you need to integrate your GitHub ID with your Apache account, so that you can merge pull requests and perform other Git tasks.
> 1. Verify you have a GitHub ID enabled with [two factor authentication (2FA)](https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/).
> 2. Merge your Apache and GitHub accounts using [Boxer](https://gitbox.apache.org/boxer/), the Apache account linking utility for GitHub. Follow the steps outlined in the linking process. You should see three green checks in Boxer when your account has been fully linked.
> 3. After about two to five minutes, you should have access to your project's repositories on GitHub.

For more details, please check https://infra.apache.org/new-committers-guide.html

**Comment by aajisaka** [comment]
Congrats and welcome @slfan1989

**Comment by slfan1989** [comment]
> Congrats and welcome @slfan1989

@aajisaka Thank you very much, I hope to help the community to do more.

**Comment by slfan1989** [comment]
> Hi @slfan1989 you'll need to follow the following steps to merge the PR via GitHub:
> 
> > To use GitHub, you need to integrate your GitHub ID with your Apache account, so that you can merge pull requests and perform other Git tasks.
> > 
> > 1. Verify you have a GitHub ID enabled with [two factor authentication (2FA)](https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/).
> > 2. Merge your Apache and GitHub accounts using [Boxer](https://gitbox.apache.org/boxer/), the Apache account linking utility for GitHub. Follow the steps outlined in the linking process. You should see three green checks in Boxer when your account has been fully linked.
> > 3. After about two to five minutes, you should have access to your project's repositories on GitHub.
> 
> For more details, please check https://infra.apache.org/new-committers-guide.html

@aajisaka Thank you very much for the information!

**Pull request merged**
