### PR TITLE
HADOOP-18677. Hadoop "current" documentation link broken after release 3.3.5.

### PR DESCRIPTION
**Pull request by cnauroth**

### CODE REVIEW

**Comment by cnauroth** [comment]
@steveloughran and @mukund-thakur , I think this is because the `current3` symlink is targeting `r.3.3.5`, but the actual directory is `r3.3.5` (extra '.'). Is this PR the right thing to do, or does this indicate some bit of automation went wrong? I've lost touch with how the release process interacts with the docs.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Review by steveloughran — APPROVED** [review]

**Comment by steveloughran** [comment]
not automation, me doing that bit by hand. sorry

**Comment by ayushtkn** [comment]
I am not sure if some automation went wrong, but in this doc if you see the point 8. f, it sounds correct to me:
``
ln -s r${version} current2
``
and version above is defined on 8.c as ``export VERSION=X.Y.Z).``
https://cwiki.apache.org/confluence/display/HADOOP2/HowToRelease

So, this PR seems right to me

**Pull request merged**
