### PR TITLE
HADOOP-18943. Fix trademark description issue of Apache on website.

### PR DESCRIPTION
**Pull request by Hexiaoqiao**
Fix trademark description issue of Apache on website.

### CODE REVIEW

**Comment by Hexiaoqiao** [comment]
cc @jojochuang @ayushtkn Please take a review. Refer detail at mail list. Thanks.

**Review by aajisaka — APPROVED** [review]
+1

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by Hexiaoqiao** [comment]
Committed. Thanks @aajisaka , @ayushtkn !

**Pull request merged**
