### PR TITLE
HDDS-3834. Add link to the documents of the edge/master

### PR DESCRIPTION
**Pull request by maobaolong**
Which from the nightly build from master branch.

### CODE REVIEW

**Comment by maobaolong** [comment]
@elek Thank you for create the nightly build job for the ozone documents site from master branch, i just add a link to the ozone document page to let people can see the edge version document easily. Please take a look, thanks.

**Review by elek — APPROVED** [review]
+1, thanks the patch @maobaolong 

Could you please execute `hugo` in the `ozone` directory and add the changes of `content` to the patch? (It's not generated automatically as far as I know)

**Comment by maobaolong** [comment]
@elek Thanks for remind me for commit the `content` to the patch. Now, I have generated it and commit it to the patch-1 branch, PTAL.

**Review by elek — APPROVED** [review]
+1, thanks the update

**Pull request merged**
