### PR TITLE
HADOOP-18943. Addendum: Fix trademark description issue of Apache on website.

### PR DESCRIPTION
**Pull request by Hexiaoqiao**
Switch to HTML character entity rather than the graphic symbols on website to improve display.

### CODE REVIEW

**Comment by Hexiaoqiao** [comment]
Addendum: TBH, I am not familiar with HTML, Please let me know if anywhere I missed, I would like to try fix it.

**Review by aajisaka — COMMENTED** [review]
Probably we don't need to add HTML tags to make the mark smaller and upper. Even in the ASF official doc https://www.apache.org/foundation/marks/list/ it doesn't have HTML tags. Therefore just using `&reg;` is fine.

**Comment by ayushtkn** [comment]
This file still has older stuff
https://github.com/Hexiaoqiao/hadoop-site/blob/trademark/content/index.html#L164
https://github.com/Hexiaoqiao/hadoop-site/blob/trademark/content/index.xml#L1427

Did you run hugo? Hugo needs to generate the .html files, we need to bother the .md file only

**Comment by Hexiaoqiao** [comment]
> Probably we don't need to add HTML tags to make the mark smaller and upper.

Got it. Let me update it for a while.

> Did you run hugo? Hugo needs to generate the .html files, we need to bother the .md file only

Let me check, I try to run `hugo server` and check it works well then submit directly.

**Comment by Hexiaoqiao** [comment]
Try to run `hugo` then `git diff --stat`, it show `174 files changed, 2584 insertions(+), 664 deletions(-)`. Is it expected? Thanks. cc @ayushtkn @aajisaka

**Comment by ayushtkn** [comment]
Your hugo version is different than the one used to built previously

**Comment by ayushtkn** [comment]
This is my diff on master after running hugo, maybe you can try this & push
```
diff --git a/content/index.html b/content/index.html
index 4944f7c6d3..6ef5783533 100644
--- a/content/index.html
+++ b/content/index.html
@@ -161,7 +161,7 @@
   limitations under the License. See accompanying LICENSE file.
 -->
 <p><img src="hadoop-logo.jpg" alt="hadoop-logo"> Apache Hadoop</p>
-<p>The Apache™ Hadoop® project develops open-source software for reliable, scalable, distributed computing.</p>
+<p>The Apache® Hadoop® project develops open-source software for reliable, scalable, distributed computing.</p>
 <p>The Apache Hadoop software library is a framework that allows for the distributed processing of large data sets across clusters of computers using simple programming models. It is designed to scale up from single servers to thousands of machines, each offering local computation and storage. Rather than rely on hardware to deliver high-availability, the library itself is designed to detect and handle failures at the application layer, so delivering a highly-available service on top of a cluster of computers, each of which may be prone to failures.</p>
 
         
diff --git a/content/index.xml b/content/index.xml
index 37d677b193..2995a199c6 100644
--- a/content/index.xml
+++ b/content/index.xml
@@ -1424,7 +1424,7 @@ A history of sustained contribution to the project. This is a way for a contribu
       
       <guid>https://hadoop.apache.org/description.html</guid>
       <description>Apache Hadoop
-The Apache™ Hadoop® project develops open-source software for reliable, scalable, distributed computing.
+The Apache® Hadoop® project develops open-source software for reliable, scalable, distributed computing.
 The Apache Hadoop software library is a framework that allows for the distributed processing of large data sets across clusters of computers using simple programming models. It is designed to scale up from single servers to thousands of machines, each offering local computation and storage. Rather than rely on hardware to deliver high-availability, the library itself is designed to detect and handle failures at the application layer, so delivering a highly-available service on top of a cluster of computers, each of which may be prone to failures.</description>
     </item>
     

```

**Comment by Hexiaoqiao** [comment]
Thanks @aajisaka and @ayushtkn . I try to update the PR: modify `src/description.md` then generate other files by `hugo`. Please take another review. Thanks again.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Review by aajisaka — APPROVED** [review]

**Comment by Hexiaoqiao** [comment]
Committed. Thanks.

**Pull request merged**
