### PR TITLE
HADOOP-19117. 3.4.0 release documents.

### PR DESCRIPTION
**Pull request by slfan1989**
JIRA: HADOOP-19117. 3.4.0 release documents.

### CODE REVIEW

**Comment by slfan1989** [comment]
@Hexiaoqiao Can you help review this pr? Thank you very much!

**Review by Hexiaoqiao — APPROVED** [review]
Huge PR and auto-generate content, right? not check every file diff, choose some of them and make sense to me. +1 from my side.

**Review by steveloughran — APPROVED** [review]
+1.

**Comment by steveloughran** [comment]
Really tips github PR review over the edge. I've trusted the generated job to be good and just verified that the links in the existing pages have been updated. All good!

**Comment by slfan1989** [comment]
@steveloughran @Hexiaoqiao Thank you very much for the review!

**Pull request merged**
