### PR TITLE
Update prabhujoseph's organization

### PR DESCRIPTION
**Pull request by GauthamBanasandra**

### CODE REVIEW

**Comment by GauthamBanasandra** [comment]
@PrabhuJoseph could you please confirm that your org is correct? Please see `src/who.md` in this commit https://github.com/apache/hadoop-site/blob/48e0bd7f58c60a6fd54b97494c31e7b771d58aa4/src/who.md

@aajisaka I just ran the `hugo` command and there seems to be a lot of formatting changes again. Is it fine to go ahead with merging this PR once @PrabhuJoseph approves? Ofcourse, we'll immediately revert this PR if the website has any issues upon merging.

**Comment by aajisaka** [comment]
Would you update `hugo` to the latest version and generate the document again? I think it will remove the extra lines generated.

**Comment by GauthamBanasandra** [comment]
Thanks @aajisaka. Using the latest version of Hugo fixed the formatting issues. I've updated the README.md file - https://github.com/apache/hadoop-site/pull/31.

@PrabhuJoseph could you please review this PR?

**Comment by aajisaka** [comment]
Thank you @GauthamBanasandra for your update. I'm +1 pending Prabhu's review.

**Comment by GauthamBanasandra** [comment]
@PrabhuJoseph could you please review?

**Pull request merged**
