### PR TITLE
chore: Update releases.md for branding

### PR DESCRIPTION
**Pull request by tisonkun**
Related discussion - https://lists.apache.org/thread/74khhy21vlhhfx0kd412xzy65mdrh3d8

cc @Hexiaoqiao

### CODE REVIEW

**Comment by Hexiaoqiao** [comment]
@tisonkun Thanks for your update. Is it the same thing with https://github.com/apache/hadoop-site/pull/46 (which is from Brand Management suggestions). Not sure if we need update registered trademark description every where or just Download page? From [1] I didn't get some explicit guide line. Any other description documents? Thank again.

[1] https://apache.org/foundation/marks/

**Comment by tisonkun** [comment]
> https://github.com/apache/hadoop-site/pull/46

Similar. While IIRC @markt-asf suggested also we can also use "Apache Hadoop®" for simply replacing "Apache® Hadoop®".

> if we need update registered trademark description every where or just Download page

If we find other references that doesn't use trademark symbols when necessary, we should fix them. But let's narrow this patch to what I noticed instead of requiring doing a full scan.

> didn't get some explicit guide line

This is a better guide I found helpful - https://www.apache.org/foundation/marks/guide#howoften. It uses Hadoop as an example and declares clearly where the "full form" should be used.

**Review by Hexiaoqiao — APPROVED** [review]
LGTM. +1.

**Comment by Hexiaoqiao** [comment]
Committed. Thanks @tisonkun .

**Pull request merged**
